version: '3.8'

services:
  jupyter:
    build:
      context: .
      dockerfile: jupyter-dockerfile
    container_name: jupyter_notebook
    ports:
      - "8888:8888"
    volumes:
      - ./tutorials:/home/jovyan/tutorials
      - ./scripts/postgresql_db.sql:/docker-entrypoint-initdb.d/postgresql_db.sql
      - ./scripts/mysql_db.sql:/docker-entrypoint-initdb.d/01_mysql_db.sql
      - ./scripts/load_data.sql:/docker-entrypoint-initdb.d/02_load_data.sql
    environment:
      JUPYTER_TOKEN: ''
    depends_on:
      - postgres_db
      - mysql_db
      - mysql_db_ddl
    networks:
      - app-network

  postgres_db:
    image: postgres:latest
    container_name: postgres_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: banking_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./scripts/postgresql_db.sql:/docker-entrypoint-initdb.d/postgresql_db.sql
    networks:
      - app-network

  mysql_db:
    image: mysql:latest
    container_name: mysql_db
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: banking_db
      MYSQL_USER: user
      MYSQL_PASSWORD: user_password
    volumes:
      - mysql_data:/var/lib/mysql
      - ./tpch_data:/var/lib/mysql-files
      - ./scripts/mysql_db.sql:/docker-entrypoint-initdb.d/01_mysql_db.sql
      - ./scripts/load_data.sql:/docker-entrypoint-initdb.d/02_load_data.sql
    networks:
      - app-network

  mysql_db_ddl:
    image: mysql:latest
    container_name: mysql_db_ddl
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: webshop_db
      MYSQL_USER: user
      MYSQL_PASSWORD: user_password
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data:
    driver: local
  mysql_data:
    driver: local
