services:
  jupyter:
    build:
      context: .
      dockerfile: jupyter-dockerfile
    container_name: jupyter_notebook
    ports:
      - "8888:8888"
    volumes:
      - ./tutorials:/home/jovyan/tutorials
    environment:
      JUPYTER_TOKEN: ''
