version: '3.8'

services:
  jupyter:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: jupyter_notebook
    ports:
      - "8888:8888"
    volumes:
      - ./tutorial.ipynb:/home/jovyan/tutorial.ipynb
      - ./postgresql_db.sql:/docker-entrypoint-initdb.d/postgresql_db.sql
      - ./mysql_db.sql:/docker-entrypoint-initdb.d/mysql_db.sql
    environment:
      JUPYTER_TOKEN: ''
    depends_on:
      - postgres_db
      - mysql_db
    networks:
      - app-network

  postgres_db:
    image: postgres:latest
    container_name: postgres_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: banking_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./postgresql_db.sql:/docker-entrypoint-initdb.d/postgresql_db.sql
    networks:
      - app-network

  mysql_db:
    image: mysql:latest
    container_name: mysql_db
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: banking_db
      MYSQL_USER: user
      MYSQL_PASSWORD: user_password
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql_db.sql:/docker-entrypoint-initdb.d/mysql_db.sql
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data:
    driver: local
  mysql_data:
    driver: local
